CREATE TABLE users (
    id TEXT UNIQUE NOT NULL PRIMARY KEY,
    login TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);

CREATE TABLE products (
    id TEXT UNIQUE NOT NULL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    categorie TEXT NOT NULL,
    image TEXT
);

CREATE TABLE categories (
    id TEXT UNIQUE NOT NULL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    image TEXT
);